const state={user:null,role:'manager',settings:null,messages:[],customers:[],orders:[],employees:[],activeCustomer:null,selectedChannel:null};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)], esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const money=n=>new Intl.NumberFormat('ar-EG').format(Number(n)||0);
async function api(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'حدث خطأ');return d}
function downloadExcel(type='all', extra={}){
  const params=new URLSearchParams({type,...extra});
  window.location.href='/api/export/excel?'+params.toString();
}
function openExportModal(type='all', title='تصدير Excel'){
  const existing=$('#exportModal'); if(existing) existing.remove();
  document.body.insertAdjacentHTML('beforeend',`<div class="modal-backdrop" id="exportModal"><div class="modal-card export-modal"><div class="modal-head"><div><h3>${esc(title)}</h3><p class="small muted">اختر الفترة والبيانات التي تريد تصديرها.</p></div><button class="icon-btn" id="closeExport">×</button></div><div class="export-grid"><div class="field"><label>الفترة</label><select id="exportPeriod"><option value="today">اليوم</option><option value="date">تاريخ محدد</option><option value="range">من تاريخ إلى تاريخ</option><option value="month">شهر محدد</option><option value="all">كل البيانات</option></select></div><div class="field" id="exportDateWrap"><label>التاريخ</label><input type="date" id="exportDate"></div><div class="field hidden" id="exportFromWrap"><label>من تاريخ</label><input type="date" id="exportFrom"></div><div class="field hidden" id="exportToWrap"><label>إلى تاريخ</label><input type="date" id="exportTo"></div><div class="field hidden" id="exportMonthWrap"><label>الشهر</label><input type="month" id="exportMonth"></div><div class="field"><label>الموظف (اختياري)</label><select id="exportEmployee"><option value="">كل الموظفين</option>${state.employees.map(e=>`<option value="${esc(e.name)}">${esc(e.name)}</option>`).join('')}</select></div></div><div class="export-help" id="exportHelp">سيتم تصدير بيانات اليوم الحالي.</div><div class="modal-actions"><button class="btn" id="cancelExport">إلغاء</button><button class="btn primary" id="confirmExport">⬇ إنشاء ملف Excel</button></div></div></div>`);
  const modal=$('#exportModal'), period=$('#exportPeriod');
  const today=new Date(); const iso=new Date(today.getTime()-today.getTimezoneOffset()*60000).toISOString().slice(0,10);
  $('#exportDate').value=iso; $('#exportMonth').value=iso.slice(0,7);
  function updateExportFields(){
    const p=period.value;
    $('#exportDateWrap').classList.toggle('hidden',p!=='date');
    $('#exportFromWrap').classList.toggle('hidden',p!=='range');
    $('#exportToWrap').classList.toggle('hidden',p!=='range');
    $('#exportMonthWrap').classList.toggle('hidden',p!=='month');
    const labels={today:'سيتم تصدير بيانات اليوم الحالي.',date:'سيتم تصدير بيانات التاريخ المحدد فقط.',range:'سيتم تصدير كل البيانات الواقعة بين التاريخين.',month:'سيتم تصدير كامل الشهر المحدد.',all:'سيتم تصدير كل البيانات الموجودة.'};
    $('#exportHelp').textContent=labels[p];
  }
  period.onchange=updateExportFields; updateExportFields();
  $('#closeExport').onclick=$('#cancelExport').onclick=()=>modal.remove();
  $('#confirmExport').onclick=()=>{
    const p=period.value, extra={period:p};
    if(p==='date') extra.date=$('#exportDate').value;
    if(p==='range'){extra.from=$('#exportFrom').value;extra.to=$('#exportTo').value; if(!extra.from||!extra.to)return toast('حدد تاريخ البداية والنهاية'); if(extra.from>extra.to)return toast('تاريخ البداية يجب أن يسبق النهاية');}
    if(p==='month') extra.month=$('#exportMonth').value;
    const emp=$('#exportEmployee').value; if(emp)extra.employee=emp;
    modal.remove(); downloadExcel(type,extra);
  };
}
function toast(msg){let root=$('#toastRoot');if(!root){root=document.createElement('div');root.id='toastRoot';document.body.appendChild(root)}root.innerHTML=`<div class="toast">${esc(msg)}</div>`;setTimeout(()=>root.innerHTML='',2800)}
function icon(x){return `<span class="nav-icon">${x}</span>`}
async function boot(){
  const health=await api('/api/health');
  if(!health.ok) throw new Error('الخادم غير جاهز');
  state.settings=await api('/api/settings');
  applyTheme();
  renderLogin();
}
function applyTheme(){document.documentElement.style.setProperty('--primary',state.settings?.primaryColor||'#6366f1')}
function renderLogin(){document.body.innerHTML=`<div class="login"><div class="login-card"><div class="login-brand"><div class="login-logo">${state.settings.logoUrl?`<img src="${esc(state.settings.logoUrl)}">`:'CK'}</div><h1>${esc(state.settings.companyName)}</h1><p>${esc(state.settings.businessType)}</p></div><div class="role-tabs"><button id="mTab" class="active">👑 مدير / مسؤول</button><button id="eTab">👤 موظف</button></div><div id="loginError" class="error hidden"></div><form id="loginForm"><div class="field"><label>اسم المستخدم</label><input id="loginUser" autocomplete="username" required></div><div class="field"><label>كلمة المرور</label><input id="loginPass" type="password" autocomplete="current-password" required></div><button class="primary" type="submit">تسجيل الدخول</button></form><div class="copyright" style="margin-top:22px">© 2026 أحمد محمد علي شخاشيرو – جميع الحقوق محفوظة</div></div></div>`;$('#mTab').onclick=()=>{state.role='manager';$('#mTab').classList.add('active');$('#eTab').classList.remove('active')};$('#eTab').onclick=()=>{state.role='employee';$('#eTab').classList.add('active');$('#mTab').classList.remove('active')};$('#loginForm').onsubmit=async e=>{e.preventDefault();try{const r=await api('/api/login',{method:'POST',body:JSON.stringify({role:state.role,username:$('#loginUser').value,password:$('#loginPass').value})});state.user=r.user;renderApp()}catch{const er=$('#loginError');er.textContent='اسم المستخدم أو كلمة المرور غير صحيحة.';er.classList.remove('hidden')}};}
function renderApp(){document.body.innerHTML=`<div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-logo">${state.settings.logoUrl?`<img src="${esc(state.settings.logoUrl)}">`:'CK'}</div><div><b>${esc(state.settings.companyName)}</b><small>${esc(state.settings.businessType)}</small></div></div><nav class="nav" id="nav"></nav><div class="side-bottom"><div class="copyright">© 2026 أحمد محمد علي شخاشيرو – جميع الحقوق محفوظة</div></div></aside><main class="main"><header class="topbar"><div style="display:flex;align-items:center"><button class="mobile-menu" id="mobileMenu">☰</button><div><h2 class="page-title" id="pageTitle">لوحة التحكم</h2><div class="crumb">نظام إدارة المبيعات وخدمة العملاء</div></div></div><div class="user-chip"><div class="avatar">${esc(state.user.name?.[0]||'م')}</div><div><b>${esc(state.user.name)}</b><div class="small muted">${state.role==='manager'?'مدير / مسؤول':'موظف'}</div></div><button class="logout ghost" id="logout">خروج</button></div></header><section class="content" id="content"></section></main><div id="modalRoot"></div></div>`;const items=state.role==='manager'?[['dashboard','▦','لوحة التحكم'],['inbox','◫','المحادثات'],['customers','♙','العملاء والمتابعات'],['orders','▣','الأوردرات'],['employees','👥','فريق العمل'],['shifts','◷','الشيفتات'],['channels','◎','القنوات'],['campaign','➤','الإرسال الجماعي'],['reports','◒','التقارير'],['settings','⚙','الإعدادات']]:[['inbox','◫','المحادثات'],['followup','↻','المتابعات'],['myshift','◷','شيفتي'],['myorders','▣','أوردراتي']];$('#nav').innerHTML=items.map((x,i)=>`<button class="${i===0?'active':''}" data-page="${x[0]}">${icon(x[1])}${x[2]}${x[0]==='inbox'?'<span id="unreadBadge" class="badge red" style="margin-right:auto;display:none">0</span>':''}</button>`).join('');$$('#nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page,b));$('#logout').onclick=()=>{state.user=null;renderLogin()};$('#mobileMenu').onclick=()=>$('#sidebar').classList.toggle('open');showPage(items[0][0],$('#nav button'));refreshData();setInterval(refreshData,8000)}
async function refreshData(){try{[state.messages,state.customers,state.orders,state.employees]=await Promise.all([api('/api/messages'),api('/api/customers'),api('/api/orders'),api('/api/employees')]);updateUnread();if($('#msgList'))renderInbox();}catch(e){} }
function updateUnread(){const n=state.messages.filter(m=>m.unread).length;const b=$('#unreadBadge');if(b){b.textContent=n;b.style.display=n?'inline-flex':'none'}}
const titles={dashboard:'لوحة التحكم',inbox:'المحادثات',customers:'العملاء والمتابعات',orders:'الأوردرات',employees:'الموظفون',shifts:'الشيفتات',channels:'القنوات',campaign:'الإرسال الجماعي',reports:'التقارير',settings:'الإعدادات',followup:'المتابعات',myshift:'شيفتي',myorders:'أوردراتي'};
function showPage(page,btn){$$('#nav button').forEach(b=>b.classList.remove('active'));btn?.classList.add('active');$('#pageTitle').textContent=titles[page]||'النظام';({dashboard, inbox:renderInbox,customers:renderCustomers,orders:renderOrders,employees:renderEmployees,shifts:renderShifts,channels:renderChannels,campaign:renderCampaign,reports:renderReports,settings:renderSettings,followup:renderFollowup,myshift:renderMyShift,myorders:renderMyOrders}[page]||dashboard)()}
function dashboard(){if(state.role!=='manager')return renderInbox();const orders=state.employees.reduce((a,x)=>a+Number(x.orders||0),0),sales=state.employees.reduce((a,x)=>a+Number(x.sales||0),0),unread=state.messages.filter(x=>x.unread).length;$('#content').innerHTML=`<div class="hero"><div><h1>صباح الخير، ${esc(state.user.name)} 👋</h1><p>إدارة المبيعات والمحادثات من لوحة واحدة.</p></div><div class="hero-actions"><button class="btn" onclick="showPage('inbox',$('#nav button[data-page=inbox]'))">فتح المحادثات</button><button class="btn" onclick="openExportModal('all','تصدير بيانات النظام')">⬇ تصدير Excel</button><button class="btn primary" onclick="showPage('settings',$('#nav button[data-page=settings]'))">إعدادات النظام</button></div></div><div class="kpis"><div class="kpi"><span class="kpi-label">أوردرات الشهر</span><div class="kpi-value">${money(orders)}</div><span class="trend">↑ أداء الفريق</span></div><div class="kpi"><span class="kpi-label">مبيعات الشهر</span><div class="kpi-value">${money(sales)} <small>${esc(state.settings.currency)}</small></div><span class="trend">للمدير فقط</span></div><div class="kpi"><span class="kpi-label">رسائل غير مقروءة</span><div class="kpi-value">${money(unread)}</div><span class="trend">تحتاج متابعة</span></div><div class="kpi"><span class="kpi-label">عملاء للمتابعة</span><div class="kpi-value">${money(state.customers.filter(x=>x.status!=='تم الطلب').length)}</div><span class="trend">Follow-up</span></div></div><div class="grid grid-2"><div class="card"><div class="card-head"><h3>أداء الموظفين</h3><span class="badge purple">هذا الشهر</span></div><div class="table-wrap"><table class="table"><thead><tr><th>الموظف</th><th>الأوردرات</th><th>المبيعات</th><th>متوسط الرد</th><th>الحالة</th></tr></thead><tbody>${state.employees.map(x=>`<tr><td><b>${esc(x.name)}</b></td><td>${money(x.orders)}</td><td>${money(x.sales)} ${esc(state.settings.currency)}</td><td>${esc(x.avg||'-')}</td><td><span class="badge ${x.status==='نشط'?'green':'yellow'}">${esc(x.status||'غير متصل')}</span></td></tr>`).join('')}</tbody></table></div></div><div class="card"><div class="card-head"><h3>حالة القنوات</h3></div>${channelCard('Messenger','🔵',state.settings.pageId&&state.settings.pageAccessToken)}${channelCard('Instagram','🟣',Boolean(state.settings.instagramAccountId))}${channelCard('WhatsApp','🟢',false)}</div></div>`}
function channelCard(name,ico,on){return `<div class="connection"><div>${ico} <b>${name}</b><div class="small muted">${on?'متصل بالإعدادات':'غير متصل بعد'}</div></div><span class="connection-dot ${on?'on':''}"></span></div>`}
function renderInbox(){const customers=state.customers;$('#content').innerHTML=`<div class="hero"><div><h1>صندوق المحادثات</h1><p>Messenger وInstagram في واجهة واحدة.</p></div><button class="btn primary" onclick="toast('سيظهر العملاء الحقيقيون تلقائياً بعد تفعيل الـWebhook')">ⓘ حالة الربط</button></div><div class="inbox"><div class="card list-card"><div class="toolbar"><input id="chatSearch" class="search" placeholder="ابحث عن عميل..."></div><div id="msgList" class="list chat-list">${customers.length?customers.map(c=>customerRow(c)).join(''):'<div class="empty">لا توجد محادثات حقيقية بعد.<br>فعّل Webhook من Meta ليظهر العملاء هنا.</div>'}</div></div><div class="card chat-window" id="chatWindow"><div class="empty">اختر محادثة من القائمة لعرض الشات كاملًا.</div></div><div class="card details-card"><div class="card-head"><h3>تفاصيل العميل</h3></div><div id="customerDetails" class="detail-list"><div class="empty">لا يوجد عميل محدد</div></div></div></div>`;$('#chatSearch').oninput=e=>{const q=e.target.value.toLowerCase();$('#msgList').innerHTML=customers.filter(c=>(c.name||'').toLowerCase().includes(q)||(c.channel||'').toLowerCase().includes(q)).map(customerRow).join('')||'<div class="empty">لا نتائج</div>'};}
function customerRow(c){return `<button class="list-row" onclick="openChat('${esc(c.id)}')"><div class="row-main"><div class="row-avatar">${esc((c.name||'ع')[0])}</div><div><b>${esc(c.name||'عميل')}</b><div class="small muted">${esc(c.channel)} · ${timeAgo(c.last)}</div></div></div><div>${c.unread?`<span class="badge red">${c.unread}</span>`:`<span class="badge green">تم الرد</span>`}</div></button>`}
function timeAgo(v){if(!v)return'';const d=Date.now()-new Date(v).getTime(),m=Math.max(1,Math.round(d/60000));return m<60?`منذ ${m} دقيقة`:m<1440?`منذ ${Math.round(m/60)} ساعة`:`منذ ${Math.round(m/1440)} يوم`}
function openChat(id){state.activeCustomer=state.customers.find(c=>String(c.id)===String(id));if(!state.activeCustomer)return;const c=state.activeCustomer;const msgs=state.messages.filter(m=>String(m.customerId)===String(c.id));$('#chatWindow').innerHTML=`<div class="chat-header"><div class="row-main"><div class="row-avatar">${esc((c.name||'ع')[0])}</div><div><b>${esc(c.name)}</b><div class="small muted">${esc(c.channel)} · ${esc(c.externalId||'')}</div></div></div><span class="badge ${c.status==='تم الطلب'?'green':'yellow'}">${esc(c.status||'لم يطلب')}</span></div><div class="chat-body">${msgs.length?msgs.slice().reverse().map(m=>`<div class="bubble ${m.direction==='outbound'?'out':'in'}">${esc(m.text)}<small>${new Date(m.time).toLocaleString('ar-EG')}</small></div>`).join(''):'<div class="empty">لا توجد رسائل محفوظة لهذا العميل.</div>'}</div><div class="composer"><div class="quick">${(state.settings.quickReplies||[]).map(q=>`<button onclick="$('#replyText').value=${JSON.stringify(q)}">${esc(q.slice(0,35))}</button>`).join('')}</div><div class="compose-row"><textarea id="replyText" placeholder="اكتب ردك هنا..."></textarea><button class="btn primary" onclick="sendCurrent()">إرسال</button></div></div>`;$('#customerDetails').innerHTML=`<div class="detail"><b>الاسم</b><br>${esc(c.name)}</div><div class="detail"><b>القناة</b><br>${esc(c.channel)}</div><div class="detail"><b>الحالة</b><br>${esc(c.status||'لم يطلب')}</div><div class="detail"><b>عدد الرسائل</b><br>${money(c.messages||0)}</div>`;state.messages.filter(m=>String(m.customerId)===String(c.id)).forEach(m=>m.unread=false);api('/api/messages/'+state.messages.find(m=>String(m.customerId)===String(c.id))?.id+'/read',{method:'POST'}).catch(()=>{});updateUnread()}
async function sendCurrent(){const text=$('#replyText')?.value.trim();const c=state.activeCustomer;if(!text||!c)return;const btn=$('.compose-row .btn.primary');btn.innerHTML='<span class="loading"></span>';try{await api('/api/send-message',{method:'POST',body:JSON.stringify({channel:c.channel,recipientId:c.externalId,text,customerId:c.id})});toast('تم إرسال الرسالة');$('#replyText').value='';await refreshData();openChat(c.id)}catch(e){toast(e.message)}finally{btn.textContent='إرسال'}}
function renderCustomers(){tablePage('العملاء','ابحث في العملاء...',state.customers,[['name','العميل'],['channel','القناة'],['status','الحالة'],['last','آخر تواصل']],['${x.name}','${x.channel}','<span class="badge yellow">${x.status||"لم يطلب"}</span>','${timeAgo(x.last)}'])}
function tablePage(title,placeholder,rows,cols,vals){$('#content').innerHTML=`<div class="hero"><div><h1>${title}</h1><p>بحث وتصفية فورية.</p></div><button class="btn" onclick="openExportModal('${title==='العملاء'?'customers':title==='الأوردرات'?'orders':title==='الموظفون'?'employees':'all'}','تصدير ${title}')">⬇ تصدير Excel</button></div><div class="card"><div class="toolbar"><input id="tableSearch" class="search" placeholder="${placeholder}"></div><div class="table-wrap"><table class="table"><thead><tr>${cols.map(c=>`<th>${c[1]}</th>`).join('')}</tr></thead><tbody id="tableBody">${renderRows(rows,vals)}</tbody></table></div></div>`;$('#tableSearch').oninput=e=>{const q=e.target.value.toLowerCase();$('#tableBody').innerHTML=renderRows(rows.filter(x=>JSON.stringify(x).toLowerCase().includes(q)),vals)}}
function renderRows(rows,vals){return rows.length?rows.map(x=>`<tr>${vals.map(v=>{try{return `<td>${eval('`'+v+'`')}</td>`}catch{return '<td>-</td>'}}).join('')}</tr>`).join(''):'<tr><td colspan="10"><div class="empty">لا توجد بيانات</div></td></tr>'}
function renderOrders(){tablePage('الأوردرات','ابحث برقم الأوردر أو العميل...',state.orders,[['id','الأوردر'],['customer','العميل'],['employee','الموظف'],['total','الإجمالي'],['date','التاريخ']],['${x.id}','${x.customer||"-"}','${x.employee||"-"}','${money(x.total)} '+state.settings.currency,'${x.date||"-"}'])}
function roleBadge(role){const cls=role==='مدير'?'purple':role==='موظف مبيعات'?'blue':'green';return `<span class="badge ${cls}">${esc(role||'-')}</span>`}
function statusBadge(status){return `<span class="badge ${status==='نشط'?'green':'red'}">${esc(status||'-')}</span>`}
function formatDate(date){if(!date)return '-';try{return new Intl.DateTimeFormat('ar-EG',{dateStyle:'medium',timeStyle:'short'}).format(new Date(date))}catch{return date}}
function openStaffModal(mode='add', employee=null){
  if(state.role!=='manager')return toast('هذه الصفحة متاحة للمدير فقط');
  const root=$('#modalRoot');
  const isEdit=mode==='edit';
  root.innerHTML=`<div class="modal-backdrop" id="staffModal"><div class="modal-card staff-modal"><div class="modal-head"><div><h3>${isEdit?'تعديل بيانات الموظف':'إضافة موظف جديد'}</h3><p class="small muted">${isEdit?'حدّث البيانات الأساسية والحالة.':'أنشئ حساباً جديداً للفريق بصلاحيات واضحة.'}</p></div><button class="icon-btn" id="staffClose" aria-label="إغلاق">×</button></div><form id="staffForm"><div class="form-grid"><div class="field full"><label>الاسم الكامل</label><input id="staffName" required maxlength=100 value="${esc(employee?.name||'')}" placeholder="مثال: أحمد محمد"></div><div class="field"><label>اسم المستخدم / البريد</label><input id="staffUsername" required ${isEdit?'disabled':''} value="${esc(employee?.username||'')}" placeholder="username أو email@example.com"></div>${isEdit?'':`<div class="field"><label>كلمة المرور</label><div class="password-wrap"><input id="staffPassword" type="password" minlength="6" required placeholder="6 أحرف على الأقل"><button type="button" class="password-toggle" data-target="staffPassword">إظهار</button></div></div>`}<div class="field"><label>الدور الوظيفي</label><select id="staffRole"><option ${employee?.role==='مدير'?'selected':''}>مدير</option><option ${employee?.role==='موظف مبيعات'?'selected':''}>موظف مبيعات</option><option ${employee?.role==='خدمة عملاء'?'selected':''}>خدمة عملاء</option></select></div><div class="field"><label>الحالة</label><select id="staffStatus"><option ${employee?.status!=='غير نشط'?'selected':''}>نشط</option><option ${employee?.status==='غير نشط'?'selected':''}>غير نشط</option></select></div></div><div class="modal-actions"><button type="button" class="btn" id="staffCancel">إلغاء</button><button type="submit" class="btn primary">${isEdit?'حفظ التعديلات':'إضافة الموظف'}</button></div></form></div></div>`;
  const close=()=>root.innerHTML='';$('#staffClose').onclick=close;$('#staffCancel').onclick=close;
  $$('.password-toggle').forEach(btn=>btn.onclick=()=>{const input=$('#'+btn.dataset.target);input.type=input.type==='password'?'text':'password';btn.textContent=input.type==='password'?'إظهار':'إخفاء'});
  $('#staffForm').onsubmit=async e=>{e.preventDefault();const name=$('#staffName').value.trim(),role=$('#staffRole').value,status=$('#staffStatus').value;if(!name)return toast('أدخل الاسم الكامل');try{let r;if(isEdit){r=await api('/api/employees/'+encodeURIComponent(employee.id),{method:'PUT',body:JSON.stringify({name,role,status})})}else{const username=$('#staffUsername').value.trim(),password=$('#staffPassword').value;if(!username)return toast('أدخل اسم المستخدم');if(password.length<6)return toast('كلمة المرور يجب أن تكون 6 أحرف على الأقل');r=await api('/api/employees',{method:'POST',body:JSON.stringify({name,username,password,role,status})})}state.employees=isEdit?state.employees.map(x=>String(x.id)===String(employee.id)?r.employee:x):[r.employee,...state.employees];close();renderEmployees();toast(isEdit?'تم تحديث بيانات الموظف':'تمت إضافة الموظف بنجاح')}catch(err){toast(err.message)}};
}
function openPasswordModal(employee){const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop" id="passwordModal"><div class="modal-card staff-modal"><div class="modal-head"><div><h3>تغيير كلمة المرور</h3><p class="small muted">إعادة تعيين كلمة مرور <b>${esc(employee.name)}</b>.</p></div><button class="icon-btn" id="passwordClose">×</button></div><form id="passwordForm"><div class="field"><label>كلمة المرور الجديدة</label><div class="password-wrap"><input id="staffNewPassword" type="password" minlength="6" required placeholder="6 أحرف على الأقل"><button type="button" class="password-toggle" data-target="staffNewPassword">إظهار</button></div><small class="muted">يجب ألا تقل عن 6 أحرف.</small></div><div class="modal-actions"><button type="button" class="btn" id="passwordCancel">إلغاء</button><button type="submit" class="btn primary">حفظ كلمة المرور</button></div></form></div></div>`;const close=()=>root.innerHTML='';$('#passwordClose').onclick=close;$('#passwordCancel').onclick=close;$('.password-toggle').onclick=()=>{const input=$('#staffNewPassword');input.type=input.type==='password'?'text':'password';$('.password-toggle').textContent=input.type==='password'?'إظهار':'إخفاء'};$('#passwordForm').onsubmit=async e=>{e.preventDefault();const password=$('#staffNewPassword').value;if(password.length<6)return toast('كلمة المرور يجب أن تكون 6 أحرف على الأقل');try{await api('/api/employees/'+encodeURIComponent(employee.id)+'/password',{method:'PUT',body:JSON.stringify({password})});close();toast('تم تغيير كلمة المرور بنجاح')}catch(err){toast(err.message)}}}
function confirmDeleteEmployee(employee){if(employee.isPrimaryManager||String(employee.username).toLowerCase()==='admin')return toast('لا يمكن حذف حساب المدير الرئيسي');const root=$('#modalRoot');root.innerHTML=`<div class="modal-backdrop"><div class="modal-card confirm-modal"><div class="confirm-icon"><i class="fa-solid fa-triangle-exclamation"></i></div><h3>حذف حساب الموظف؟</h3><p class="muted">سيتم حذف حساب <b>${esc(employee.name)}</b> نهائياً ولا يمكن التراجع عن العملية.</p><div class="modal-actions"><button class="btn" id="deleteCancel">إلغاء</button><button class="btn danger-fill" id="deleteConfirm">نعم، حذف الموظف</button></div></div></div>`;$('#deleteCancel').onclick=()=>root.innerHTML='';$('#deleteConfirm').onclick=async()=>{try{await api('/api/employees/'+encodeURIComponent(employee.id),{method:'DELETE'});state.employees=state.employees.filter(x=>String(x.id)!==String(employee.id));root.innerHTML='';renderEmployees();toast('تم حذف الموظف')}catch(err){toast(err.message)}}}
function renderEmployees(){
  if(state.role!=='manager')return;
  const query=($('#employeeSearch')?.value||'').trim().toLowerCase();
  const rows=state.employees.filter(x=>!query||[x.name,x.username,x.role,x.status].join(' ').toLowerCase().includes(query));
  $('#content').innerHTML=`<div class="hero"><div><h1>فريق العمل</h1><p>إدارة حسابات الموظفين والأدوار والحالات وكلمات المرور من مكان واحد.</p></div><button class="btn primary" id="addEmployeeBtn"><i class="fa-solid fa-user-plus"></i> إضافة موظف جديد</button></div><div class="card"><div class="staff-toolbar"><div><strong>${state.employees.length}</strong> حسابات في الفريق</div><input id="employeeSearch" class="search" placeholder="بحث بالاسم أو اسم المستخدم أو الدور..." value="${esc(query)}"></div><div class="table-wrap"><table class="table staff-table"><thead><tr><th>الموظف</th><th>اسم المستخدم</th><th>الدور الوظيفي</th><th>الحالة</th><th>تاريخ الإنشاء</th><th>الإجراءات</th></tr></thead><tbody>${rows.map(x=>`<tr><td><div class="staff-person"><div class="staff-avatar">${esc((x.name||'م')[0])}</div><div><b>${esc(x.name)}</b>${x.isPrimaryManager?'<div class="small muted">الحساب الرئيسي</div>':''}</div></div></td><td><span class="username-pill">${esc(x.username)}</span></td><td>${roleBadge(x.role)}</td><td>${statusBadge(x.status)}</td><td>${formatDate(x.createdAt)}</td><td><div class="staff-actions"><button class="action-btn" data-action="edit" data-id="${esc(x.id)}" title="تعديل البيانات"><i class="fa-solid fa-pen"></i></button><button class="action-btn" data-action="password" data-id="${esc(x.id)}" title="تغيير كلمة المرور"><i class="fa-solid fa-key"></i></button><button class="action-btn danger" data-action="delete" data-id="${esc(x.id)}" title="حذف" ${x.isPrimaryManager?'disabled':''}><i class="fa-solid fa-trash"></i></button></div></td></tr>`).join('')||'<tr><td colspan="6"><div class="empty">لا توجد حسابات تطابق البحث.</div></td></tr>'}</tbody></table></div></div>`;
  $('#addEmployeeBtn').onclick=()=>openStaffModal('add');
  $('#employeeSearch').oninput=()=>renderEmployees();
  $$('.staff-actions .action-btn').forEach(btn=>btn.onclick=()=>{const employee=state.employees.find(x=>String(x.id)===String(btn.dataset.id));if(!employee)return;const action=btn.dataset.action;if(action==='edit')openStaffModal('edit',employee);if(action==='password')openPasswordModal(employee);if(action==='delete')confirmDeleteEmployee(employee)});
}

function renderShifts(){renderEmployees()}
function renderReports(){if(state.role!=='manager')return;$('#content').innerHTML=`<div class="hero"><div><h1>التقارير</h1><p>ملخص الأداء الحالي.</p></div><button class="btn" onclick="openExportModal('all','تصدير التقارير')">⬇ تصدير Excel</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>الموظف</th><th>الأوردرات</th><th>المبيعات</th><th>متوسط الرد</th></tr></thead><tbody>${state.employees.map(x=>`<tr><td>${esc(x.name)}</td><td>${money(x.orders)}</td><td>${money(x.sales)} ${esc(state.settings.currency)}</td><td>${esc(x.avg||'-')}</td></tr>`).join('')}</tbody></table></div></div>`}
function renderChannels(){const channels=[
['Messenger','🔵','Page ID',state.settings.pageId,Boolean(state.settings.pageId&&state.settings.pageAccessToken)],
['Instagram','🟣','Instagram Account ID',state.settings.instagramAccountId,Boolean(state.settings.instagramAccountId&&state.settings.pageAccessToken)],
['WhatsApp','🟢','Phone Number ID',state.settings.whatsappPhoneNumberId,state.settings.whatsappEnabled&&Boolean(state.settings.whatsappPhoneNumberId&&state.settings.whatsappAccessToken)]
];$('#content').innerHTML=`<div class="hero"><div><h1>القنوات</h1><p>Messenger وInstagram وWhatsApp جاهزة للإضافة من الإعدادات.</p></div><button class="btn primary" onclick="showPage('settings',$('#nav button[data-page=settings]'))">إعدادات القنوات</button></div><div class="grid grid-2">${channels.map(c=>`<div class="card"><div class="card-head"><h3>${c[1]} ${c[0]}</h3><span class="connection-dot ${c[4]?'on':''}"></span></div><p class="muted small">${c[2]}: ${esc(c[3]||'غير مضبوط')}</p><p class="small">${c[4]?'متصل':'غير متصل حالياً'}</p></div>`).join('')}</div>`}
function renderCampaign(){const candidates=state.customers.filter(c=>c.status!=='تم الطلب');$('#content').innerHTML=`<div class="hero"><div><h1>الإرسال الجماعي</h1><p>حدد العملاء الذين تريد متابعتهم ثم أرسل قالباً جاهزاً.</p></div></div><div class="card"><div class="toolbar"><input id="campSearch" class="search" placeholder="بحث..."><button class="btn" onclick="selectAllCampaign(true)">تحديد الكل</button><button class="btn primary" onclick="toast('الإرسال الجماعي يحتاج قناة Meta مفعلة وصلاحيات إرسال')">إرسال المحددين</button></div><div class="list" id="campList">${candidates.map(c=>`<label class="list-row"><div class="row-main"><input type="checkbox" class="camp-check" value="${c.id}"><div class="row-avatar">${esc((c.name||'ع')[0])}</div><div><b>${esc(c.name)}</b><div class="small muted">${esc(c.channel)} · ${esc(c.status||'لم يطلب')}</div></div></div></label>`).join('')||'<div class="empty">لا يوجد عملاء للمتابعة.</div>'}</div></div>`}
function selectAllCampaign(v){$$('.camp-check').forEach(x=>x.checked=v)}
function renderFollowup(){renderCustomers()}
function renderMyShift(){const e=state.user;$('#content').innerHTML=`<div class="hero"><div><h1>شيفتي</h1><p>معلومات الشيفت الحالية.</p></div></div><div class="card"><h3>${esc(e.name)}</h3><p class="muted">الشيفت: ${esc(e.shift||'-')}</p><div class="kpis"><div class="kpi"><span class="kpi-label">الأوردرات</span><div class="kpi-value">${money(e.orders)}</div></div><div class="kpi"><span class="kpi-label">متوسط الرد</span><div class="kpi-value">${esc(e.avg||'-')}</div></div></div></div>`}
function renderMyOrders(){const mine=state.orders.filter(o=>o.employee===state.user.name);tablePage('أوردراتي','بحث...',mine,[['id','الأوردر'],['customer','العميل'],['total','الإجمالي'],['date','التاريخ']],['${x.id}','${x.customer||"-"}','${money(x.total)} '+state.settings.currency,'${x.date||"-"}'])}
function renderSettings(){if(state.role!=='manager')return;const s=state.settings;$('#content').innerHTML=`<div class="hero"><div><h1>الإعدادات</h1><p>تخصيص White-Label وإعدادات Meta دون تعديل الكود.</p></div><button class="btn primary" id="saveSettings">حفظ التغييرات</button></div><div class="settings-grid"><div class="card"><div class="card-head"><h3>هوية النظام</h3><span class="badge purple">White-Label</span></div><div class="form-grid"><div class="field"><label>اسم الشركة / النشاط</label><input id="companyName" value="${esc(s.companyName)}"></div><div class="field"><label>نوع النشاط</label><input id="businessType" value="${esc(s.businessType)}"></div><div class="field"><label>العملة الافتراضية</label><select id="currency"><option ${s.currency==='EGP'?'selected':''}>EGP</option><option ${s.currency==='USD'?'selected':''}>USD</option><option ${s.currency==='SYP'?'selected':''}>SYP</option></select></div><div class="field"><label>الضريبة الافتراضية %</label><input id="tax" type="number" min="0" step="0.01" value="${esc(s.tax||0)}"></div><div class="field"><label>الشحن الافتراضي</label><input id="shipping" type="number" min="0" step="0.01" value="${esc(s.shipping||0)}"></div><div class="field"><label>اللون الأساسي</label><div class="color-row"><input type="color" id="primaryColor" value="${esc(s.primaryColor)}"><input id="primaryColorText" value="${esc(s.primaryColor)}"></div></div><div class="field full"><label>رابط الشعار (اختياري)</label><div style="display:flex;gap:10px"><input id="logoUrl" value="${esc(s.logoUrl)}"><button class="btn" id="uploadLogoBtn">رفع صورة</button><input type="file" id="logoFile" accept="image/png,image/jpeg,image/webp" class="hidden"></div></div></div></div><div class="card"><div class="card-head"><h3>Meta API</h3><span class="badge ${s.pageAccessToken?'green':'yellow'}">${s.pageAccessToken?'مضبوط':'يحتاج إعداد'}</span></div><div class="field"><label>Page ID</label><input id="pageId" value="${esc(s.pageId)}"></div><div class="field"><label>Page Access Token</label><input id="pageAccessToken" type="password" placeholder="أدخل التوكن عند تغييره"><small class="muted">يُحفظ في data/settings.json. في بيئة إنتاج حقيقية يفضل Secret Manager.</small></div><div class="field"><label>Verify Token</label><input id="verifyToken" value="${esc(s.verifyToken)}"></div><div class="field"><label>Graph API Version</label><input id="graphVersion" value="${esc(s.graphVersion)}"></div><div class="field"><label>Instagram Account ID</label><input id="instagramAccountId" value="${esc(s.instagramAccountId)}"></div>
<div class="card-subsection" style="margin-top:16px;padding-top:16px;border-top:1px solid var(--border)"><h4>WhatsApp Cloud API</h4><p class="small muted">الإعدادات موجودة من الآن، ويمكنك تفعيلها لاحقاً عندما يصبح الرقم معك.</p>
<div class="form-grid"><div class="field"><label>Phone Number ID</label><input id="whatsappPhoneNumberId" value="${esc(s.whatsappPhoneNumberId||'')}"></div><div class="field"><label>WhatsApp Business Account ID</label><input id="whatsappBusinessAccountId" value="${esc(s.whatsappBusinessAccountId||'')}"></div><div class="field full"><label>WhatsApp Access Token</label><input id="whatsappAccessToken" type="password" placeholder="أدخل التوكن عند الربط"></div></div>
<label style="display:flex;gap:8px;align-items:center;margin-top:10px"><input type="checkbox" id="whatsappEnabled" ${s.whatsappEnabled?'checked':''}> تفعيل WhatsApp</label></div><label style="display:flex;gap:8px;align-items:center;margin-top:12px"><input type="checkbox" id="autoReply" ${s.autoReplyEnabled?'checked':''}> تفعيل الردود التلقائية</label><div style="margin-top:14px;display:flex;gap:8px"><button class="btn" onclick="testConnection()">اختبار الاتصال</button><button class="btn danger" onclick="resetDemo()">تفريغ البيانات التجريبية</button></div></div></div><div class="card" style="margin-top:18px"><div class="card-head"><h3>حساب الدخول</h3><span class="badge purple">${esc(state.user.username)}</span></div><div class="form-grid"><div class="field"><label>كلمة المرور الحالية</label><input id="currentPassword" type="password"></div><div class="field"><label>كلمة المرور الجديدة</label><input id="newPassword" type="password" minlength="6"></div></div><button class="btn" onclick="changePassword()">تغيير كلمة المرور</button></div>
<div class="card" style="margin-top:18px"><div class="card-head"><h3>قوالب الرد السريع</h3><button class="btn" onclick="addQuickReply()">+ إضافة قالب</button></div><div id="quickSettings" class="list">${(s.quickReplies||[]).map((q,i)=>`<div style="display:flex;gap:8px"><input class="search quick-setting" data-i="${i}" value="${esc(q)}"><button class="btn danger" onclick="this.parentElement.remove()">حذف</button></div>`).join('')}</div></div>`;$('#primaryColor').oninput=e=>$('#primaryColorText').value=e.target.value;$('#primaryColorText').oninput=e=>{if(/^#[0-9a-f]{6}$/i.test(e.target.value))$('#primaryColor').value=e.target.value};$('#saveSettings').onclick=saveSettings;$('#uploadLogoBtn').onclick=()=>$('#logoFile').click();$('#logoFile').onchange=uploadLogo}
function addQuickReply(){const root=$('#quickSettings');const div=document.createElement('div');div.style='display:flex;gap:8px';div.innerHTML='<input class="search quick-setting" value=""><button class="btn danger">حذف</button>';div.querySelector('button').onclick=()=>div.remove();root.appendChild(div)}
async function saveSettings(){const quick=$$('.quick-setting').map(x=>x.value.trim()).filter(Boolean);const body={companyName:$('#companyName').value,businessType:$('#businessType').value,currency:$('#currency').value,tax:Number($('#tax').value||0),shipping:Number($('#shipping').value||0),primaryColor:$('#primaryColorText').value,logoUrl:$('#logoUrl').value,pageId:$('#pageId').value,verifyToken:$('#verifyToken').value,graphVersion:$('#graphVersion').value,instagramAccountId:$('#instagramAccountId').value,whatsappPhoneNumberId:$('#whatsappPhoneNumberId').value,whatsappBusinessAccountId:$('#whatsappBusinessAccountId').value,whatsappEnabled:$('#whatsappEnabled').checked,autoReplyEnabled:$('#autoReply').checked,quickReplies:quick};if($('#pageAccessToken').value.trim())body.pageAccessToken=$('#pageAccessToken').value.trim();
if($('#whatsappAccessToken').value.trim())body.whatsappAccessToken=$('#whatsappAccessToken').value.trim();try{const r=await api('/api/settings',{method:'POST',body:JSON.stringify(body)});state.settings=r.settings;applyTheme();toast('تم حفظ الإعدادات وتطبيقها فوراً');renderApp()}catch(e){toast(e.message)}}
async function uploadLogo(){const f=$('#logoFile').files[0];if(!f)return;const fd=new FormData();fd.append('logo',f);try{const r=await fetch('/api/settings/logo',{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error);$('#logoUrl').value=d.logoUrl;toast('تم رفع الشعار');}catch(e){toast(e.message)}}
async function testConnection(){
  try{
    const r=await api('/api/settings/test-connection',{method:'POST',body:JSON.stringify({channel:'messenger'})});
    toast(r.ok ? `تم الاتصال بنجاح: ${r.data?.name||'Meta Page'}` : 'فشل الاتصال');
  }catch(e){toast(e.message)}
}
async function resetDemo(){if(!confirm('سيتم حذف الرسائل والعملاء والأوردرات التجريبية. هل أنت متأكد؟'))return;await api('/api/reset-demo',{method:'POST'});toast('تم تفريغ البيانات التجريبية');refreshData()}
async function changePassword(){const current=$('#currentPassword').value,newPass=$('#newPassword').value;if(!current||newPass.length<6)return toast('كلمة المرور الجديدة يجب أن تكون 6 أحرف على الأقل');try{await api('/api/change-password',{method:'POST',body:JSON.stringify({role:state.role,username:state.user.username,currentPassword:current,newPassword:newPass})});toast('تم تغيير كلمة المرور بنجاح');$('#currentPassword').value='';$('#newPassword').value='';}catch(e){toast(e.message)}}
boot().catch(e=>{document.body.innerHTML=`<div class="login"><div class="login-card"><h2>تعذر تشغيل النظام</h2><p>${esc(e.message)}</p></div></div>`});
